### ISSUE TITLE
how can i add new one client id

### ISSUE THREAD

**Issue by eric-hon** [RichardKnop/go-oauth2-server#11]
in the test samples have two client id,test_client_1,test_client_2 and passwords.
how can i add new one client id?
thanks!

**Comment by RichardKnop** [comment]
Do you mean in tests or when running live?

Right now there is only an option to connect to the database and run insert query.

In tests, you could add more test data to fixtures.

**Comment by eric-hon** [comment]
thanks,in tests,the client secret how to generate ?
below client secret how how to generate ?
table: 'oauth_clients'
  pk:
    id: 1
  fields:
    key: 'test_client_1'
    secret: '$2a$10$CUoGytf1pR7CC6Y043gt/.vFJUV4IRqvH5R6F0VfITP8s2TqrQ.4e'
    redirect_uri: 'https://www.example.com'
    created_at: 'ON_INSERT_NOW()'
    updated_at: 'ON_UPDATE_NOW()'

**Comment by eric-hon** [comment]
the secret of th client key how to generate ?

**Comment by RichardKnop** [comment]
Run from Postgres shell:

```sql
select crypt('new password', gen_salt('bf'));
```

You might need to enable `pgcrypto` extension first if you haven't done it yet:

```
CREATE EXTENSION pgcrypto;
```

**Comment by eric-hon** [comment]
thanks!
and when running live, add the more client data is the same above? if not ,how to ?

**Comment by eric-hon** [comment]
that's ok,thanks!
