### ISSUE TITLE
dependent package  errors

### ISSUE THREAD

**Issue by eric-hon** [RichardKnop/go-oauth2-server#13]
make update-deps:
godep: Package (golang.org/x/net/context) not found

make install-deps:
unrecognized import path "golang.org/x/crypto/bcrypt
unrecognized import path "golang.org/x/crypto/blowfish"
unrecognized import path "golang.org/x/net/context"

and how to solved it ?

**Comment by RichardKnop** [comment]
Do you have Go environment setup properly?

What do you see here:

```
ls $GOPATH/src
```

**Comment by eric-hon** [comment]
No found golang.org forder

**Comment by eric-hon** [comment]
the Go environment is correct：
export GOROOT=/usr/local/go
export GOPATH=/home/eric/go
export PATH=$GOROOT/bin:$GOPATH/bin:$PATH

put the link golang.org/x/net/context to webbrowser,display is "no found the web" and then redirect to https://godoc.org/golang.org/x/net/context

**Comment by eric-hon** [comment]
i see, that't ok!
