### ISSUE TITLE
Docker-compose issue: not starting after cloning the repo

### ISSUE THREAD

**Issue by katsar0v** [RichardKnop/go-oauth2-server#14]
> INFO: 2016/09/20 07:40:55 factory.go:154 ETCD Endpoint: http://etcd:2379
> INFO: 2016/09/20 07:40:55 factory.go:100 Successfully loaded config for the first time
> INFO: 2016/09/20 07:40:55 factory.go:154 ETCD Endpoint: http://etcd:2379
> INFO: 2016/09/20 07:40:55 factory.go:100 Successfully loaded config for the first time
> INFO: 2016/09/20 07:40:55 factory.go:154 ETCD Endpoint: http://etcd:2379
> INFO: 2016/09/20 07:40:55 factory.go:100 Successfully loaded config for the first time
> Error loading file accounts/fixtures/roles.yml: open accounts/fixtures/roles.yml: no such file or directory

This happens when I git clone the repo and write docker-compose up

Docker version: 1.12.1
Docker-compose: 1.8.0

**Comment by RichardKnop** [comment]
@katsar0v Try now. Should be fixed.
