### ISSUE TITLE
Problem migrate from PostgreSQL to MySQL

### ISSUE THREAD

**Issue by fwso** [RichardKnop/go-oauth2-server#16]
When I was trying to migrate from PostgreSQL to MySQL, it took more effort than I thought. Due to the inconsistent data type of IDs, when `gorm` try to create foreign key, following error occurs:

```
Error 1215: Cannot add foreign key constraint
```

`gorm` defines the ID with `unit` type, which maps to MySQL `int(10) unsigned`:

```
package gorm

import "time"

type Model struct {
    ID        uint `gorm:"primary_key"`
    CreatedAt time.Time
    UpdatedAt time.Time
    DeletedAt *time.Time `sql:"index"`
}
```

But `ClientID`, `UserID` defined as `sql.NullInt64`, which map to MySQL `bigint(20)`:

```
type RefreshToken struct {
    gorm.Model
    ClientID  sql.NullInt64 `sql:"index;not null"`
    UserID    sql.NullInt64 `sql:"index"`
    Client    *Client
    User      *User
    Token     string    `sql:"type:varchar(40);unique;not null"`
    ExpiresAt time.Time `sql:"not null"`
    Scope     string    `sql:"type:varchar(200);not null"`
}
```

**Comment by RichardKnop** [comment]
@fwso Yes I agree. I should have just used `int64` everywhere. Not sure why I used `uint` for primary keys. This should be refactored. Feel free to submit your changes as PR!

**Comment by kira8565** [comment]
I change the `sql.NullInt64` to uint and migrate to mysql,every thing looks fine......But unit tests may need to be adjusted.....

**Comment by adam-hanna** [comment]
Does this fork help? I changed all ID's to uuids generated in go.

https://github.com/adam-hanna/go-oauth2-server/tree/feature/uuid
