### ISSUE TITLE
FATAL: 2016/12/03 16:47:02 factory.go:84 key not found: /config/go_oauth2_server.json

### ISSUE THREAD

**Issue by kira8565** [RichardKnop/go-oauth2-server#19]
I install etdc and set the go_oauth2_server.json. after set the config,i  use 

```
etcdctl get  /config/go_oauth2_server.json
```
i see my config is success

and after i install pg,i run  `./go-oauth2-server migrate`
but i got this message

```
INFO: 2016/12/03 16:41:29 factory.go:169 ETCD Endpoints: http://127.0.0.1:2379
FATAL: 2016/12/03 16:41:29 factory.go:84 key not found: /config/go_oauth2_server.json

```

i do not know why ,i think my config is right

**Comment by RichardKnop** [comment]
@kira8565 I have migrated config to use etcd v3 API:

Try adding this to your `~/.bash_profile`:

```
export ETCDCTL_API=3
```

Then check your `etcdctl` client is using API version 3:

```
Richards-MacBook-Pro:you-ledger richardknop$ etcdctl version
etcdctl version: 3.0.9
API version: 3.0
```

^^ You should see `API version: 3.0`, then it should work.

**Comment by kira8565** [comment]
:+1: The problem is solved

**Comment by Kulak** [comment]
I run into the same issue.  I was using docker-compose.yaml file.  The issue certainly was related to API version.  In my case, I had to add lines:

```
    environment:
      - ETCDCTL_API=3
```

to file that creates etcd containers.
