### ISSUE TITLE
User data

### ISSUE THREAD

**Issue by ggitau** [RichardKnop/go-oauth2-server#2]
When inserting user data.Is there a utility to help with that?(some package,with some method). How do we hash the passwords.bcrypt,md5?

**Comment by RichardKnop** [comment]
In the `oauth` package there are couple of utility methods I defined and use in the `web` package for registration / login. For example:

https://github.com/RichardKnop/go-oauth2-server/blob/master/oauth/user.go#L32

```go
// CreateUser saves a new user to database
func (s *Service) CreateUser(username, thePassword string) (*User, error) {
	passwordHash, err := password.HashPassword(thePassword)
	if err != nil {
		return nil, errors.New("Bcrypt error")
	}
	user := User{
		Username: username,
		Password: string(passwordHash),
	}
	if err := s.db.Create(&user).Error; err != nil {
		return nil, errors.New("Error saving user to database")
	}
	return &user, nil
}
```

Users are very simple structs with just username and password:

```go
type User struct {
	ID        int64  `gorm:"primary_key"`
	Username  string `sql:"type:varchar(254);unique;not null"`
	Password  string `sql:"type:varchar(60);not null"`
	CreatedAt time.Time
	UpdatedAt time.Time
}
```

I wanted to keep the `oauth` package as minimal as possible though so it's easy to build upon in your own project.

The idea is to build your own models on top of the `oauth` package. So in the accounts package, which is empty now and serves no purpose, you could create new models on top of `oauth.Client` and `oauth.User`.

**Comment by RichardKnop** [comment]
@ggitau Here is oauth.ServiceInterface which defines all exported methods of the `oauth` package:

```go
// ServiceInterface defines exported methods
type ServiceInterface interface {
	ClientExists(clientID string) bool
	FindClientByClientID(clientID string) (*Client, error)
	CreateClient(clientID, secret, redirectURI string) (*Client, error)
	AuthClient(clientID, secret string) (*Client, error)
	UserExists(username string) bool
	FindUserByUsername(username string) (*User, error)
	CreateUser(username, thePassword string) (*User, error)
	AuthUser(username, thePassword string) (*User, error)
	GetScope(requestedScope string) (string, error)
	GrantAuthorizationCode(client *Client, user *User, redirectURI, scope string) (*AuthorizationCode, error)
	GrantAccessToken(client *Client, user *User, scope string) (*AccessToken, error)
	GetOrCreateRefreshToken(client *Client, user *User, scope string) (*RefreshToken, error)
	GetValidRefreshToken(token string, client *Client) (*RefreshToken, error)
	Authenticate(token string) error
}
```

https://github.com/RichardKnop/go-oauth2-server/blob/master/oauth/interfaces.go

**Comment by ggitau** [comment]
Thanks @RichardKnop

**Comment by jmheidly** [comment]
Hi Richard,
I highly appreciate your efforts with developing q very interesting oauth server.
We're planning to fork and do some changes pertaining to the database services. Mainly abstract the database interface and remove the coupling on gorm and as a result integrate nosql databases.
Let me know what are your plans going forward :)
RegardsJamal

Sent from Outlook




On Wed, Nov 18, 2015 at 10:20 PM -0800, "ggitau" <notifications@github.com> wrote:












Thanks @RichardKnop
