### ISSUE TITLE
Is there a plan to support the management interface

### ISSUE THREAD

**Issue by kira8565** [RichardKnop/go-oauth2-server#20]
I think go-oauth2-server is a very good project, is there a plan to support the management interface and some Rest API to  go-oauth2-server like user role management ? If  have these functions, other services can no longer consider user management, role management such a basic module(`･ω･´)

**Comment by RichardKnop** [comment]
@kira8565 I don't have any immediate plans to support any management interface. Feel free to submit a PR if you happen to be working on anything like that.

The way I am looking at it, I was trying to keep the `oauth2` package as decoupled as possible and only include code implementing OAuth2 spec.

You could build more complicated user management system around it but I would probably create a new package for that.

Take a look at this experimental project: https://github.com/RichardKnop/example-api

I took the `go-oauth2-server` as a starting point and added user management on top of it (creating, updating, listing users, sending confirmation email, resetting password, inviting users etc), basic roles (superadmin and regular user), also it includes a Facebook login endpoint so you can have a frontend which allows both username/password and Facebook login and have the access token managed by yourself.

**Comment by kira8565** [comment]
｡◕‿◕｡

**Comment by RichardKnop** [comment]
@kira8565 All APIs are documented here with curl examples: https://github.com/kira8565/example-api/tree/master/docs
