### ISSUE TITLE
ctx is attached with a deadline is exceeded: context deadline exceeded

### ISSUE THREAD

**Issue by malk2013** [RichardKnop/go-oauth2-server#23]
Hello,
i am on Windows 8 with golang env installed , I have cloned the go-oauth2-server , i have postgresql latest installed , now i run fo-oauth2-server migrate it i sshowing me error "*ctx is attached with a deadline is exceeded: context deadline exceeded"
I have created "go-oauth2-server" DB and user through pgadmin3 , what extra steps i have to take .
I want to run this and test it locally first which later will be deployed as microservice on docker

Please help

**Comment by adam-hanna** [comment]
I was getting that same error and it's because I didn't have etcd running. have you run `etcd` and have you loaded the config?
