### ISSUE TITLE
struggling to get database initialized properly

### ISSUE THREAD

**Issue by belveder79** [RichardKnop/go-oauth2-server#24]
Hi,
Despite having the same issue with docker-compose as in #21, after restarting it multiple times it seems to bring up everything. However, the database is not populated with the user accounts nor the test clients. I tried to enter the information by hand, but it's quite a mess. With docker-compose, shouldn't it enter all the information automatically?
Best
Clemens

**Comment by RichardKnop** [comment]
@belveder79 Sorry for late reply. You can insert test data from fixtures via docker exec. See example here: 

https://github.com/RichardKnop/go-oauth2-server#docker
