### ISSUE TITLE
UUID rather than sequential integers for id's (possible pull request)

### ISSUE THREAD

**Issue by adam-hanna** [RichardKnop/go-oauth2-server#28]
Sorry to be spamming the issues board today...

I thought I'd take a stab at modifying the codebase to use uuid's rather than sequential ints for ids. Let me know your thoughts on the below. It passes all tests and should be sql engine agnostic as the uuid's are generated in go code rather than in the db.
https://github.com/adam-hanna/go-oauth2-server/tree/feature/uuid

It's a few commits behind this repo and needs some linting / general cleanup but it's mostly there. Let me know your thoughts and I will get it up to current, clean it up and get it ready for a pull request.

Thanks!

**Comment by RichardKnop** [comment]
It's probably better to use UUIDs rather than sequential ids for table rows. I have seen before people still use integers for primary keys but have them randomly generated rather then auto incremented, this is often done in financial industry. But UUIDs seem like a better solution to me.

**Comment by adam-hanna** [comment]
> If the tests will be passing I would probably consider merging this into master. I also noticed in your github some JWT related Golang code.

Thanks! I'll work on getting a PR together.

Also, more than happy to work on a jwt pr as well!
