### ISSUE TITLE
[Question] Use for cmd line authentication/authorization

### ISSUE THREAD

**Issue by alok87** [RichardKnop/go-oauth2-server#38]
**What?**

I see the code is structured to use for web app only. Can it be used for authentication/authorization of command line tool? What needs to be done to achieve it.

**Comment by RaniSputnik** [comment]
Hi Alok, this is a SERVER implementation of oath2, it provides the authority on identity. If you are set on using oauth for your authentication, then you’re going to want an oauth CLIENT for your command tool (something like https://github.com/golang/oauth2).

**Comment by RichardKnop** [comment]
As @RaniSputnik has said, you can use the oauth2 client implementation from Golang standard library for that.

Basically this application acts as a server and if you have services / apps that need to authenticated agains this server, just use the client oauth2 library to obtain access token from there.
