### ISSUE TITLE
password grant type

### ISSUE THREAD

**Issue by pjebs** [RichardKnop/go-oauth2-server#47]
Thanks @RichardKnop for the package.

I was wondering if the password  grant type was a future feature or actually implemented?

**Comment by RichardKnop** [comment]
@pjebs It is implemented. Implicit, client credentials, password credentials and authorisation grants are all implemented.

**Comment by pjebs** [comment]
Is it easy to get running with mysql?

**Comment by RichardKnop** [comment]
Should be quite easy, there is no SQL, all database comms is handled via orm which supports all major RDBSs.

**Comment by pjebs** [comment]
One of the reasons I wasn't sure was because the entire project has a dependency for the postgres driver.

Is there a possibility you will remove the gorilla context package as a dependency from the dep file?

**Comment by RichardKnop** [comment]
@pjebs You might contribute with a PR to use the core library context instead of gorilla. This was written before that was available.
