### ISSUE TITLE
Add registration and profile managment

### ISSUE THREAD

**Issue by wolfeidau** [RichardKnop/go-oauth2-server#5]
Just wondering if you were open to some additions around signup, registration and profile management.

Need it for a side project.

**Comment by RichardKnop** [comment]
@wolfeidau There is an empty package `accounts` in this repo meant to be filled with stuff like signup, permissions, profile management etc.

Currently not planning to include anything specific here as I would like to keep this project completely agnostic dealing with only oauth2. Different people manage accounts/profiles, permissions and so on differently.
