### ISSUE TITLE
Checksum Mismatch Running go install

### ISSUE THREAD

**Issue by aviezab** [RichardKnop/go-oauth2-server#60]
Dear,
As mentioned in README.md, I have tried run `go install .` after running latest etcd binary (3.4.0 rc3), and found this error:
```
verifying github.com/coreos/etcd@v3.3.12+incompatible: checksum mismatch
	downloaded: h1:pAWNwdf7QiT1zfaWyqCtNZQWCLByQyA3JrSQyuYAqnQ=
	go.sum:     h1:5k8nkcBSvltjOO5RLflnXevOJXndlKIMbvVnMTX+cUU=

```
I found no binary compiled cause of this. Any suggestion?

**Comment by rexfordnyrk** [comment]
Hello, @aviezab kindly delete the `go.sum` file in the root of the project directory and try building again, you should be fine. please close this issue after that. Thank you.

**Comment by aviezab** [comment]
@rexfordnyrk Thanks for answer. Closing.
